[package]
name = "simplesat"
version = "0.1.0"
authors = ["Hanliang Zhang <hanliangzhang.cm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-error = "0.1.1"


[dev-dependencies]
proptest = "1.0.0"